name: ci

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Lint (black)
        run: black --check .

      - name: Sort imports (isort)
        run: isort --check-only .

      - name: Lint (flake8)
        run: flake8 .

      - name: Type check (mypy)
        run: mypy src

      - name: Ensure artifacts dir
        run: mkdir -p artifacts

      - name: Run pipeline (produce artifacts)
        run: |
          python -m src.pipeline

      - name: Run tests with coverage
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=xml

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts
          path: |
            artifacts/**
            coverage.xml
            .coverage
          if-no-files-found: warn
