name: model-ci
on:
  workflow_dispatch:
  push:
    paths:
      - "app/**"
      - "requirements.txt"
      - ".github/workflows/model-ci.yml"

jobs:
  train-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train model
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -m app.train
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            artifacts/model.pkl
            artifacts/metrics.json
